"""Small end-to-end sample set for Member 6 mapping demos."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from app.schemas.detection import DetectionResult
from app.schemas.event import (
    AttackInfo,
    HostInfo,
    NetworkInfo,
    NormalizedEvent,
    ObjectInfo,
    SubjectInfo,
)


BASE_TIME = datetime(2026, 9, 8, 10, 0, tzinfo=timezone.utc)


@dataclass(frozen=True)
class SampleScenario:
    event: NormalizedEvent
    detection: DetectionResult


def build_sample_scenarios() -> list[SampleScenario]:
    return [
        _scenario(
            seq=1,
            minute=0,
            source_type="network_traffic",
            source="suricata",
            hostname="WEB01",
            ip="10.0.1.10",
            event_type="network_connection",
            action="exploit",
            analyzer="exploit_analyzer",
            detection_type="malicious_behavior",
            title="Web shell upload to public web application",
            description="SQL injection followed by webshell upload",
            severity="critical",
            confidence=0.94,
            tags=["exploit", "web_shell", "rce"],
            subject=None,
            object_=None,
            network=NetworkInfo(src_ip="203.0.113.10", dst_ip="10.0.1.10", dst_port=443),
            evidence={"signature": "ET WEB_SERVER webshell upload"},
            entity_ids=["host:WEB01", "ip:10.0.1.10"],
        ),
        _scenario(
            seq=2,
            minute=2,
            source_type="host_behavior",
            source="windows_sysmon",
            hostname="WEB01",
            ip="10.0.1.10",
            event_type="process_create",
            action="create_process",
            analyzer="process_analyzer",
            detection_type="malicious_behavior",
            title="PowerShell encoded command execution",
            description="powershell.exe -enc SQBFAFgA...",
            severity="high",
            confidence=0.91,
            tags=["powershell", "process"],
            subject=SubjectInfo(type="process", name="powershell.exe", pid=4123, user="www-data"),
            object_=None,
            network=None,
            evidence={"command_line": "powershell.exe -enc SQBFAFgA..."},
            entity_ids=["host:WEB01", "process:WEB01:4123", "user:WEB01:www-data"],
        ),
        _scenario(
            seq=3,
            minute=8,
            source_type="host_behavior",
            source="windows_sysmon",
            hostname="WEB01",
            ip="10.0.1.10",
            event_type="registry_modify",
            action="modify_registry",
            analyzer="host_behavior_analyzer",
            detection_type="malicious_behavior",
            title="Registry Run key persistence",
            description="Malicious executable added to HKLM Run key",
            severity="high",
            confidence=0.88,
            tags=["persistence", "registry"],
            subject=None,
            object_=ObjectInfo(type="registry", name="HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"),
            network=None,
            evidence={"key": "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"},
            entity_ids=["host:WEB01", "registry:WEB01:HKLM-Run"],
        ),
        _scenario(
            seq=4,
            minute=12,
            source_type="host_behavior",
            source="ebpf",
            hostname="PC01",
            ip="10.0.1.30",
            event_type="process_inject",
            action="inject_code",
            analyzer="process_injection_analyzer",
            detection_type="malicious_behavior",
            title="Suspicious process injection into lsass.exe",
            description="Reflective DLL injection into LSASS process",
            severity="critical",
            confidence=0.93,
            tags=["process_injection", "lsass"],
            subject=SubjectInfo(type="process", name="malware.exe", pid=3301),
            object_=ObjectInfo(type="process", name="lsass.exe", pid=3302),
            network=None,
            evidence={"technique": "reflective_loader"},
            entity_ids=["host:PC01", "process:PC01:3301", "process:PC01:3302"],
        ),
        _scenario(
            seq=5,
            minute=16,
            source_type="host_log",
            source="windows_security",
            hostname="PC01",
            ip="10.0.1.30",
            event_type="log_clear",
            action="clear_log",
            analyzer="log_analyzer",
            detection_type="malicious_behavior",
            title="Windows event log cleared",
            description="Security event log was cleared by an attacker",
            severity="high",
            confidence=0.9,
            tags=["indicator_removal", "log_cleanup"],
            subject=None,
            object_=None,
            network=None,
            evidence={"event_id": 1102},
            entity_ids=["host:PC01"],
        ),
        _scenario(
            seq=6,
            minute=20,
            source_type="host_behavior",
            source="windows_sysmon",
            hostname="PC01",
            ip="10.0.1.30",
            event_type="file_read",
            action="read_file",
            analyzer="credential_access_analyzer",
            detection_type="malicious_behavior",
            title="Mimikatz credential dump activity",
            description="Access to SAM database and LSASS memory",
            severity="critical",
            confidence=0.95,
            tags=["credential_access", "mimikatz"],
            subject=SubjectInfo(type="process", name="mimikatz.exe", pid=3410),
            object_=ObjectInfo(type="file", name="C:\\Windows\\System32\\config\\SAM"),
            network=None,
            evidence={"accessed_file": "C:\\Windows\\System32\\config\\SAM"},
            entity_ids=["host:PC01", "file:PC01:C:\\Windows\\System32\\config\\SAM"],
        ),
        _scenario(
            seq=7,
            minute=25,
            source_type="network_traffic",
            source="zeek",
            hostname="PC01",
            ip="10.0.1.30",
            event_type="network_scan",
            action="scan",
            analyzer="scan_analyzer",
            detection_type="malicious_behavior",
            title="Internal port scan",
            description="Horizontal port scan across internal subnet",
            severity="medium",
            confidence=0.86,
            tags=["scan", "discovery"],
            subject=None,
            object_=None,
            network=NetworkInfo(src_ip="10.0.1.30", dst_ip="10.0.1.0/24", dst_port=445),
            evidence={"ports": [22, 445, 3389]},
            entity_ids=["host:PC01", "ip:10.0.1.30"],
        ),
        _scenario(
            seq=8,
            minute=30,
            source_type="network_traffic",
            source="zeek",
            hostname="PC01",
            ip="10.0.1.30",
            event_type="network_connection",
            action="authenticate",
            analyzer="lateral_movement_analyzer",
            detection_type="malicious_behavior",
            title="SMB lateral movement to database server",
            description="Remote service access using stolen credentials",
            severity="high",
            confidence=0.92,
            tags=["lateral_movement", "smb"],
            subject=None,
            object_=None,
            network=NetworkInfo(src_ip="10.0.1.30", dst_ip="10.0.1.40", dst_port=445),
            evidence={"protocol": "smb", "user": "dbadmin"},
            entity_ids=["host:PC01", "host:DB01", "ip:10.0.1.40"],
        ),
        _scenario(
            seq=9,
            minute=35,
            source_type="host_behavior",
            source="linux_auditd",
            hostname="DB01",
            ip="10.0.1.40",
            event_type="file_read",
            action="read_file",
            analyzer="file_monitor_analyzer",
            detection_type="suspicious_behavior",
            title="Sensitive database file read",
            description="Unexpected read of customer database files",
            severity="medium",
            confidence=0.84,
            tags=["collection", "sensitive_file"],
            subject=SubjectInfo(type="process", name="mysql", pid=778),
            object_=ObjectInfo(type="file", name="/var/lib/mysql/customer.ibd"),
            network=None,
            evidence={"path": "/var/lib/mysql/customer.ibd"},
            entity_ids=["host:DB01", "file:DB01:/var/lib/mysql/customer.ibd"],
        ),
        _scenario(
            seq=10,
            minute=42,
            source_type="network_traffic",
            source="zeek",
            hostname="PC01",
            ip="10.0.1.30",
            event_type="dns_query",
            action="resolve",
            analyzer="dns_tunnel_analyzer",
            detection_type="malicious_behavior",
            title="Potential DNS tunnel",
            description="High entropy DNS labels to unusual domain",
            severity="high",
            confidence=0.91,
            tags=["dns", "tunnel"],
            subject=None,
            object_=None,
            network=NetworkInfo(src_ip="10.0.1.30", dst_ip="8.8.8.8", protocol="dns"),
            evidence={"query_count": 328, "avg_domain_length": 57.2},
            entity_ids=["host:PC01", "domain:evil.example.com", "ip:8.8.8.8"],
        ),
        _scenario(
            seq=11,
            minute=50,
            source_type="network_traffic",
            source="suricata",
            hostname="DB01",
            ip="10.0.1.40",
            event_type="data_upload",
            action="upload",
            analyzer="exfil_analyzer",
            detection_type="malicious_behavior",
            title="Data exfiltration over C2",
            description="Large outbound transfer to known C2",
            severity="critical",
            confidence=0.9,
            tags=["exfiltration", "data_upload"],
            subject=None,
            object_=None,
            network=NetworkInfo(src_ip="10.0.1.40", dst_ip="198.51.100.20", protocol="https"),
            evidence={"bytes": 18743296},
            entity_ids=["host:DB01", "ip:198.51.100.20"],
        ),
        _scenario(
            seq=12,
            minute=60,
            source_type="host_behavior",
            source="windows_sysmon",
            hostname="FS01",
            ip="10.0.1.60",
            event_type="file_modify",
            action="encrypt_file",
            analyzer="ransomware_analyzer",
            detection_type="malicious_behavior",
            title="Ransomware encryption activity",
            description="Mass file encryption and ransom note",
            severity="critical",
            confidence=0.97,
            tags=["ransomware", "impact", "encrypt"],
            subject=SubjectInfo(type="process", name="ransom.exe", pid=5120),
            object_=ObjectInfo(type="file", name="E:\\Shares\\customer.docx"),
            network=None,
            evidence={"encrypted_files": 1200},
            entity_ids=["host:FS01", "file:FS01:E:\\Shares\\customer.docx"],
        ),
        _scenario(
            seq=13,
            minute=3,
            source_type="host_behavior",
            source="windows_sysmon",
            hostname="WIN10",
            ip="10.0.1.50",
            event_type="process_create",
            action="create_process",
            analyzer="process_analyzer",
            detection_type="anomaly",
            title="Routine svchost process creation",
            description="Normal service host process started",
            severity="info",
            confidence=0.7,
            tags=["normal"],
            subject=SubjectInfo(type="process", name="svchost.exe", pid=1800),
            object_=None,
            network=None,
            evidence={"parent_process": "services.exe"},
            entity_ids=["host:WIN10", "process:WIN10:1800"],
        ),
        _scenario(
            seq=14,
            minute=7,
            source_type="network_traffic",
            source="zeek",
            hostname="WIN10",
            ip="10.0.1.50",
            event_type="dns_query",
            action="resolve",
            analyzer="dns_analyzer",
            detection_type="anomaly",
            title="Normal DNS resolution",
            description="Routine DNS lookup for update server",
            severity="info",
            confidence=0.6,
            tags=["normal"],
            subject=None,
            object_=None,
            network=NetworkInfo(src_ip="10.0.1.50", dst_ip="10.0.1.2", protocol="dns"),
            evidence={"query": "update.internal"},
            entity_ids=["host:WIN10", "ip:10.0.1.50"],
        ),
    ]


def build_sample_detections() -> list[DetectionResult]:
    return [scenario.detection for scenario in build_sample_scenarios()]


def build_sample_events() -> list[NormalizedEvent]:
    return [scenario.event for scenario in build_sample_scenarios()]


def _scenario(
    *,
    seq: int,
    minute: int,
    source_type: str,
    source: str,
    hostname: str,
    ip: str,
    event_type: str,
    action: str,
    analyzer: str,
    detection_type: str,
    title: str,
    description: str,
    severity: str,
    confidence: float,
    tags: list[str],
    subject: SubjectInfo | None,
    object_: ObjectInfo | None,
    network: NetworkInfo | None,
    evidence: dict,
    entity_ids: list[str],
) -> SampleScenario:
    timestamp = BASE_TIME + timedelta(minutes=minute)
    event_id = f"evt-{seq:03d}"
    detection_id = f"det-{seq:03d}"

    event = NormalizedEvent(
        event_id=event_id,
        timestamp=timestamp,
        source_type=source_type,
        source=source,
        host=HostInfo(hostname=hostname, ip=ip, os=_infer_os(source)),
        event_type=event_type,
        subject=subject,
        object=object_,
        network=network,
        action=action,
        severity=severity,
        tags=tags,
        raw_data={"sample": True},
    )

    detection = DetectionResult(
        detection_id=detection_id,
        timestamp=timestamp,
        analyzer=analyzer,
        detection_type=detection_type,
        title=title,
        description=description,
        severity=severity,
        confidence=confidence,
        related_event_ids=[event_id],
        related_entity_ids=entity_ids,
        evidence=evidence,
        tags=tags,
    )

    return SampleScenario(event=event, detection=detection)


def _infer_os(source: str) -> str | None:
    if source in {"windows_sysmon", "windows_security", "ebpf"}:
        return "windows"
    if source == "linux_auditd":
        return "linux"
    return None
